# 02_shape_broadcast

对应 `index.md` 第 2 阶段：reshape / view / permute、broadcast、contiguous。

笔记本在 `codes/pytorch/02_shape_broadcast/qa.ipynb`。需要读写文件时，工作空间就是这个目录。

先运行下一格，得到 `ROOT`。每题只改 `# 作答` 下面的代码。前置代码不用改。做完自己跑通即可，先不要对答案。


In [1]:
from pathlib import Path

def lab_root() -> Path:
    """qa.ipynb 所在目录。"""
    here = Path.cwd().resolve()
    for folder in [here, *here.parents]:
        if folder.name == "02_shape_broadcast" and (folder / "qa.ipynb").is_file():
            return folder
        candidate = folder / "codes" / "pytorch" / "02_shape_broadcast"
        if (candidate / "qa.ipynb").is_file():
            return candidate
    return here

ROOT = lab_root()
ROOT


PosixPath('/Users/keyficller/Documents/AEFS-Notes/codes/pytorch/02_shape_broadcast')

## 1. reshape 改形状

把一维的 `t` 改成形状 `(3, 4)`，打印改形后的张量，再打印它的 `shape`。


In [4]:
import torch

t = torch.arange(12)

# 作答

import torch

rhp = t.reshape(3, 4)
print(rhp)
print(rhp.shape)
#评阅
# 对。reshape(3, 4)，张量与 shape 都打印了。

#参考答案
# y = t.reshape(3, 4)
# print(y)
# print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


## 2. view 改形状

`t` 是连续的一维张量。用 `view` 把它变成 `(2, 3)`，打印结果及其 `shape`。


In [5]:
import torch

t = torch.arange(6)

# 作答

import torch

viw = t.view(2, 3)
print(viw)
print(viw.shape)
#评阅
# 对。连续张量上用 view(2, 3) 正确。

#参考答案
# y = t.view(2, 3)
# print(y)
# print(y.shape)

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])


## 3. permute 调维序

`x` 的形状是 `(2, 3, 4)`。用 `permute` 把维序改成「原第 1 维、原第 0 维、原第 2 维」，即目标形状 `(3, 2, 4)`。

打印 permute 之后的 `shape`。


In [6]:
import torch

x = torch.arange(24).reshape(2, 3, 4)

# 作答

import torch

perm = x.permute(1, 0, 2)
print(x.shape)
print(perm.shape)
#评阅
# 对。permute(1, 0, 2) 得到 (3, 2, 4)。多打了原 shape 无妨。

#参考答案
# print(x.permute(1, 0, 2).shape)

torch.Size([2, 3, 4])
torch.Size([3, 2, 4])


## 4. 广播相加

`a` 形状 `(3, 1)`，`b` 形状 `(3,)`。计算 `a + b`（依赖广播），打印结果，再打印结果的 `shape`。


In [8]:
import torch

a = torch.ones(3, 1)
b = torch.arange(3.0)

# 作答
# 3 x 1 
# 1 x 3 
# align to 3 x 3
sum = a + b
print(sum)
print(sum.shape)
#评阅
# 对。广播到 (3, 3)，结果也对。变量名 sum 会盖掉内置函数，下次换个名字更好。

#参考答案
# out = a + b
# print(out)
# print(out.shape)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])
torch.Size([3, 3])


## 5. 不连续后再 view

`y` 来自转置，一般**不连续**。先打印 `y.is_contiguous()`。

再得到一份与 `y` 同值、但是连续的张量，打印它的 `is_contiguous()`。

最后对这份连续张量用 `view` 变成形状 `(12,)`，打印最终 `shape`。


In [9]:
import torch

x = torch.arange(12).reshape(3, 4)
y = x.t()

# 作答

print(y.is_contiguous())

print(y.contiguous())
print(y.contiguous().is_contiguous())

print(y.contiguous().view(12))
print(y.contiguous().view(12).shape)
#评阅
# 对。先看不连续，再 contiguous，最后 view(12)。多次调用 contiguous() 可以，赋给变量一次更干净。

#参考答案
# print(y.is_contiguous())
# z = y.contiguous()
# print(z.is_contiguous())
# print(z.view(12).shape)

False
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
True
tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])
torch.Size([12])
