# 01_tensor_basics

对应 `index.md` 第 1 阶段：Tensor 创建、索引、形状 / dtype / device、基础运算。

笔记本在 `codes/pytorch/01_tensor_basics/qa.ipynb`。需要读写文件时，工作空间就是这个目录。

先运行下一格，得到 `ROOT`。每题只改 `# 作答` 下面的代码。前置代码不用改。做完自己跑通即可，先不要对答案。


In [1]:
from pathlib import Path

def lab_root() -> Path:
    """qa.ipynb 所在目录。"""
    here = Path.cwd().resolve()
    for folder in [here, *here.parents]:
        if folder.name == "01_tensor_basics" and (folder / "qa.ipynb").is_file():
            return folder
        candidate = folder / "codes" / "pytorch" / "01_tensor_basics"
        if (candidate / "qa.ipynb").is_file():
            return candidate
    return here

ROOT = lab_root()
ROOT


PosixPath('/Users/keyficller/Documents/AEFS-Notes/codes/pytorch/01_tensor_basics')

## 1. 从列表建张量，再造同形全零

用 `torch.tensor` 从 `data` 建一个张量并打印。

再用工厂函数建一个与它**同形状**的全 0 张量，打印出来。


In [3]:
import torch

data = [[1, 2], [3, 4]]

# 作答

import torch

print(torch.tensor(data))
#评阅
# 缺一半。tensor(data) 对了，但还要用工厂函数建同形状全 0 并打印（如 zeros_like 或 zeros(x.shape)）。

#参考答案
# x = torch.tensor(data)
# print(x)
# print(torch.zeros_like(x))

tensor([[1, 2],
        [3, 4]])


## 2. ones 与 arange

用工厂函数建一个形状为 `(2, 3)`、元素全为 1 的张量，打印。

再用 `arange` 建一维张量，值为 `0, 1, 2, 3, 4, 5`（到 5 为止，不含 6），打印。


In [5]:
import torch

# 作答

import torch

print(torch.ones(2, 3))
print(torch.arange(0, 6))
#评阅
# 对。ones(2, 3) 与 arange(0, 6) 都对（arange(6) 等价）。

#参考答案
# print(torch.ones(2, 3))
# print(torch.arange(6))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 1, 2, 3, 4, 5])


## 3. 索引与切片

对已有张量 `t`，按这个顺序打印三项：

1. 第 1 行（行下标从 0 起）
2. 左上角 `2×2` 子块
3. 最后一列


In [6]:
import torch

t = torch.tensor(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
    ]
)

# 作答

import torch

print(t[0])
print(t[:2, :2])
print(t[:, -1])
#评阅
# 后两项对。第一项题意是行下标 1（第二行 [4,5,6,7]），应是 t[1]，不是 t[0]。

#参考答案
# print(t[1])
# print(t[:2, :2])
# print(t[:, -1])

tensor([0, 1, 2, 3])
tensor([[0, 1],
        [4, 5]])
tensor([ 3,  7, 11])


## 4. shape、dtype、device，再改精度

依次打印 `x` 的 `shape`、`dtype`、`device`。

再把 `x` 转成 `float32`（可用 `.float()` 或 `.to(...)`），打印转换后张量的 `dtype`。


In [7]:
import torch

x = torch.tensor([1, 2, 3])

# 作答

import torch

print(x.shape)
print(x.dtype)
print(x.device)

print(x.float())
print(x.to(torch.float32))
#评阅
# 前三项对。最后要打印的是转换后的 dtype，不是整个 float 张量；写 x.float().dtype 或 x.to(torch.float32).dtype。

#参考答案
# print(x.shape, x.dtype, x.device)
# print(x.float().dtype)

torch.Size([3])
torch.int64
cpu
tensor([1., 2., 3.])
tensor([1., 2., 3.])


## 5. 逐元素运算与归约

对 `a`、`b`：打印 `a + b`，再打印 `a * b`（逐元素乘）。

对 `m`：打印全体元素之和；再打印按 `dim=0`（沿行方向压掉）的均值。


In [8]:
import torch

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([10.0, 20.0, 30.0])
m = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# 作答

import torch

print(a + b)
print(a * b)

print(m.sum(dim=None))
print(m.mean(dim=0))
#评阅
# 对。逐元素加减乘、全体 sum、dim=0 的 mean 都正确（sum() 不写 dim 也行）。

#参考答案
# print(a + b)
# print(a * b)
# print(m.sum())
# print(m.mean(dim=0))

tensor([11., 22., 33.])
tensor([10., 40., 90.])
tensor(10.)
tensor([2., 3.])
